### ISSUE TITLE
Add NFS HA cluster configuration template and split brain script

### ISSUE THREAD

**Issue by arbulu89** [SUSE/drbd-formula#15]
By now, we don't ship the HA NFS share configuration template in this package (as we do in other formulas).
I think that using HA DRBD to serve a NFS share is really common, so having the cluster template here makes total sense.
We have received some feedback from customers, that they don't have the cluster configuration, and I think having it here makes sense, than copy/pasting from other sources.

By now, these files are stored in:

[NFS cluster resources](https://github.com/SUSE/ha-sap-terraform-deployments/blob/develop/salt/drbd_node/files/templates/drbd_cluster.j2)  (I would call it `nfs_cluster_resources.j2`)
[Split brain script](https://github.com/SUSE/ha-sap-terraform-deployments/blob/develop/salt/drbd_node/files/notify-split-brain-haclusterexporter-suse-metric.sh)

@nick-wang What do you think?

**Comment by nick-wang** [comment]
Yes, i think better to have a cluster configuration here as well, or even only have it here.
As long as we have a usage/scenario [documentation](https://github.com/SUSE/drbd-formula/blob/master/examples/README.md).
I have some basic configuration [examples](https://github.com/SUSE/drbd-formula/tree/master/examples)

I think the templates (cluster/split-brain) is couple to the ha-sap-terraform project, like it use grains like `cloud_provider`. So i would like to store it in another folder of [the examples](https://github.com/SUSE/drbd-formula/tree/master/examples) together with [the generic one](https://github.com/SUSE/drbd-formula/blob/master/examples/with_pacemaker/drbd_with_nfs_crm.j2) for cluster.

**Comment by arbulu89** [comment]
@nick-wang Ok, we will need to find the correct formula to do so.
Will you take care of this?

**Comment by arbulu89** [comment]
@nick-wang Actually, I didn't know we had these examples already on the project. I guess we don't ship them in the rpm, package. We will need to do so. Ship the nfs template, and the split brain script.

**Comment by nick-wang** [comment]
@arbulu89 Sure, i can take this. 
I can add these templates to formula first, them use it in terraform project.
 
I think it is not in a high priority, will do it after fixed a SP3 kernel submission blocker issue:(
